# This pyinstaller spec file was generated by /Users/rauhanahmedrizvi/Desktop/gdbtest/gdbgui/make_executable.py

block_cipher = None


a = Analysis(['gdbgui/cli.py'],  # noqa
             pathex=['.'],
             binaries=[],
             datas=[
              ('./gdbgui/static*', './static'),
              ('./gdbgui/templates*', './templates'),
              ('./gdbgui/VERSION.txt*', './')
            ],
             hiddenimports=[
               'engineio.async_threading',
               'engineio.async_drivers.threading',
               'pkg_resources.py2_warn',
               ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             )

pyz = PYZ(a.pure, a.zipped_data,  # noqa
             cipher=block_cipher)

exe = EXE(pyz,  # noqa
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name="gdbgui_0.15.0.1",
          debug=False,
          strip=False,
          upx=False,
          runtime_tmpdir=None,
          console=True)

